import type { Metadata } from "next";
import "./globals.css";

import { Provider } from "./project-provider"
import {  getDocuments } from 'outstatic/server';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const projects = await getDocuments("projects", ['title', 'url', 'video', 'type', 'tags', 'metrics', 'content', 'color']);
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <Provider value={projects}>
        <body>{children}</body>
      </Provider>
    </html>
  );
}
