import type { Metadata } from "next";
import "./globals.css";

import { ProjectProvider } from "./project-provider";
import { DemoProvider } from "./demo-provider";
import { getDocuments } from "outstatic/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const projects = await getDocuments("projects", [
    "title",
    "url",
    "video",
    "type",
    "tags",
    "metrics",
    "content",
    "color",
  ]);
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <ProjectProvider value={projects}>
        <body>{children}</body>
      </ProjectProvider>
    </html>
  );
}
